### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooltools#10]
Title says it all, using `cooltools` requires `distributed`, but it's not in dependencies, so has to be installed manually.

**Comment by Phlya** [comment]
Also `cytoolz`

**Comment by nvictus** [comment]
Yup. The `install_requires` in setup.py can be updated. I think pip handles these dependencies alright.

**Comment by Phlya** [comment]
It should, yes, they are both in pypi - just mentioning them here for you to add them yourself (in case the version is important, perhaps).

**Comment by Phlya** [comment]
Also `numba`
