### ISSUE TITLE
An argument for having a `--vrange` option in saddle CLI

### ISSUE THREAD

**Issue by sergpolly** [mirnylab/cooltools#12]
Right now we are binning values from a track file between a pair of percentiles defined by `--prange`.
Some people would like to use CLI version of saddle to do a nuanced analysis on individual chromosomes in `cis` and/or a pair (or selected subset of pairs) of chromosomes in `trans`. In such a scenario, `prange`-based binning leads to inconsistent bins across different subset of chromosomes/pairs, i.e. providing track-files for different combinations of chromosomes leads to different `prange` values ...

Thus, it seems like a good idea to introduce a `--vrange` option for the saddle CLI,  that would enable a user to manually define the left and right limits of the value-range to get binned, thus providing consistent binning across multiple different track-files.

Another option is to let users reuse `binedges` defined for one track-file to the other  - as a file input.

Which one seems more general/preferable ?!

I'm in favor of `--vrange` (it's easy to implement!) with an explicit documentation and notion of some of the danger that `vrange` brings with it

**Comment by nvictus** [comment]
+1 for `--vrange`

**Comment by golobor** [comment]
+1 for --vrange too!

**Comment by sergpolly** [comment]
--vrange option added https://github.com/mirnylab/cooltools/pull/13
