### ISSUE TITLE
Eigen vector not calculated on the covariance matrix?

### ISSUE THREAD

**Issue by dearxxj** [mirnylab/cooltools#123]
Hi, I just started to explore Cooltools recently. It's such a great tool that facilitates Hi-C analysis. Thank you all for your efforts!

I had a question about the way Cooltools calls AB compartments. It seems that the eigen vector decomposition is not performed on the covariance matrix?

https://github.com/mirnylab/cooltools/blob/9c8028f756865f8315096419b3d32bc7d6560bed/cooltools/lib/numutils.py#L500

If I understand it correctly, AB compartments are demarcated by the first principle components (PC1). I've seen in literatures that people calculate PC1 by performing eigen vector decomposition on the covariance/correlation matrix of the OE matrix. I'm wondering why cooltools uses a different approach?

**Comment by mimakaev** [comment]
Hi, 

The results of the two methods are almost completely the same. Also, in (Imakaev, 2012) we do not do PCA and do a simple eigenvector decomposition. Here, we choose a computationally simpler eigenvector decompostion, and not a PCA. 

The mathematical explanation of the similarity is as follows. PCA involves two steps: mean-centering the rows, and calculating the covariance matrix. After taking the observed-over-expected transofmration, the sum over rows of the matrix is roughly constant. Therefore, mean-centering the rows roughly subtracts a constant from the matrix, and roughly keeps the matrix symmetric. Taking a covariance of that symmetric matrix is therefore roughly equivalent to the dot product of a symmetric matrix with itself. However, the dot product of the matrix with itself has the same eigenvectors as the original matrix. This is discussed in the methods of (Imakaev, 2012); however, in that case the matrix was strictly doubly stochastic, and therefore the two results were strictly equal. 

In reality the sums over the rows of the observed-over-expected matrix are slightly variable, which causes the two approaches to give slightly different results. I was not able to find which of them is more correct, therefore I prefer a simpler eigenvector decomposition.

**Comment by dearxxj** [comment]
Thank you for the explanation of the relation between the two methods. I found the results are very similar too, but didn't understand the underlying mathematical relationship.
