### ISSUE TITLE
dot-caller chroms are floats not ints

### ISSUE THREAD

**Issue by gspracklin** [mirnylab/cooltools#125]
cooltools call-dots -p 20 -o Unsync_10kb.bedpe -v ../Unsynchronized.hg38.mapq_30.1000.mcool::/resolutions/10000 ../expected/Unsynchronized.10000.cis.expected.txt.noYMT.txt

Issue is likely during to the clustering step: https://github.com/mirnylab/cooltools/blob/9c8028f756865f8315096419b3d32bc7d6560bed/cooltools/dotfinder.py#L1770 

Seems unrelated to:
1. chrY and chrMT
2. Deep v sparse data 

[Unsync_10kb.bedpe.centroids.txt](https://github.com/mirnylab/cooltools/files/3957216/Unsync_10kb.bedpe.centroids.txt)
[Unsync_10kb.bedpe.filteredpixelsannotated.txt](https://github.com/mirnylab/cooltools/files/3957217/Unsync_10kb.bedpe.filteredpixelsannotated.txt)
[Unsync_10kb.bedpe.filteredpixelsqvals.txt](https://github.com/mirnylab/cooltools/files/3957218/Unsync_10kb.bedpe.filteredpixelsqvals.txt)
[Unsync_10kb.bedpe.postproc.txt](https://github.com/mirnylab/cooltools/files/3957219/Unsync_10kb.bedpe.postproc.txt)
[Unsync_10kb.bedpe.txt](https://github.com/mirnylab/cooltools/files/3957220/Unsync_10kb.bedpe.txt)

**Comment by sergpolly** [comment]
sort of fixed now...
but there might have been more explicit solution - to use `observed=True` is pandas `groupby`:
```
observed : bool, default False
    This only applies if any of the groupers are Categoricals.
    If True: only show observed values for categorical groupers.
    If False: show all values for categorical groupers.
```

closing for now

**Comment by sergpolly** [comment]
keep this https://github.com/pandas-dev/pandas/issues/17594 here

**Comment by gspracklin** [comment]
observed=True in groupby fixed the issue as well
