### ISSUE TITLE
call-compartments: object 'weight' doesn't exist

### ISSUE THREAD

**Issue by ZhangJiankun21** [mirnylab/cooltools#129]
Hi, I run "cooltools compute-expected" successfully with "--weight-name KR". Then I realized "cooltools call-compartments" doesn't have this option. I got the error described in the title when running "cooltools call-compartments". Do you have any suggestions to solve this?

`   +-- 500000
         +-- bins
         |   +-- GW_KR (6189,) float64
         |   +-- GW_SCALE (6189,) float64
         |   +-- GW_VC (6189,) float64
         |   +-- INTER_KR (6189,) float64
         |   +-- INTER_SCALE (6189,) float64
         |   +-- INTER_VC (6189,) float64
         |   +-- KR (6189,) float64
         |   +-- SCALE (6189,) float64
         |   +-- VC (6189,) float64
         |   +-- VC_SQRT (6189,) float64
         |   +-- chrom (6189,) int32
         |   +-- end (6189,) int32
         |   +-- start (6189,) int32
         +-- chroms
         |   +-- length (25,) int32
         |   +-- name (25,) |S32
         +-- indexes
         |   +-- bin1_offset (6190,) int64
         |   +-- chrom_offset (26,) int64
         +-- pixels
             +-- bin1_id (16288151,) int64
             +-- bin2_id (16288151,) int64
             +-- count (16288151,) int32`

**Comment by nvictus** [comment]
Hi! The option to choose the weight column actually [exists](https://github.com/mirnylab/cooltools/blob/master/cooltools/eigdecomp.py#L296), but isn't exposed via the CLI yet.

Until it's available, you can try replicating what the CLI is doing from Python, adding `balance="KR"` to the function call: https://github.com/mirnylab/cooltools/blob/master/cooltools/cli/call_compartments.py#L148-L166

If by any chance you'd be interested in making a PR, let me know. The solution would be to expose these [same two options](https://github.com/mirnylab/cooltools/blob/master/cooltools/cli/compute_expected.py#L59-L72) to `call-compartments`. Note that `balance=True` defaults to the column name `"weight"`, and `balance={some string}` uses a custom weight column name.

**Comment by ZhangJiankun21** [comment]
Great! Thanks for the help.
