### ISSUE TITLE
Make saddle-strength nan-aware

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooltools#137]
Sometimes might get nan output from `cooltools.saddle.saddle_strength` if there are NaNs in the saddle data. Is there any objection to simply replacing `.sum()` with `np.nansum()` everywhere?

https://github.com/mirnylab/cooltools/blob/30d2b06be55f1dafbd529ffb05dde274e64664e2/cooltools/saddle.py#L556-L561

**Comment by nvictus** [comment]
I can't think of any. Go ahead!

**Comment by sergpolly** [comment]
closing this since it's been done
