### ISSUE TITLE
compute-saddle running error

### ISSUE THREAD

**Issue by JhinAir** [mirnylab/cooltools#143]
Hi,

when I computed saddle with command:
**cooltools compute-saddle chr1_2_3.cool chr1_2_3.cis.vecs.tsv chr1_2_3.cis.expected.tsv --strength -o chr1_2_3 --fig pdf**;
such errors kept throwing out:

> ValueError: Chromosomes in chr1_2_3.cis.vecs.tsv must be subset of chromosomes in expected chr1_2_3.cis.expected.tsv.

I'm confused that it worked fine with some chromosomes, but not for others. I have double-checked that the bins and chromosomes are the same in these two .tsv files. Could you please help to find the reason? 
I used commands to get input.tsv files: 
**cooltools call-compartments chr1_2_3.cool -o chr1_2_3 --reference-track chr1_2_3.GC;
cooltools compute-expected chr1_2_3.cool -o chr1_2_3.cis.expected.tsv**
All files are attached. Thanks very much.
[chr1_2_3.zip](https://github.com/mirnylab/cooltools/files/4263990/chr1_2_3.zip)

Jing

**Comment by itsameerkat** [comment]
Hi Jing,

I don't know if you've already figure this out or not but your vector table is not properly formatted. Specifically, your chrom column need to a string with the format 'chr{#}' i.e 'chr1', 'chr2', and 'chr3'.
