### ISSUE TITLE
in numutils, the Cython and Numba versions iterative_correction_symmetric have the same name

### ISSUE THREAD

**Issue by golobor** [mirnylab/cooltools#15]
https://github.com/mirnylab/cooltools/blob/f7132ed93d92d540b9357a83834788f93c52e0e1/cooltools/num/numutils.py#L449

**Comment by nvictus** [comment]
I renamed the cython extensions for `numutils` to just `_numutils`. If someone wants to use cython duplicates of numba functions in `numutils`, they can be made available with a leading underscore (2ff2117).

**Comment by golobor** [comment]
thank you!
