### ISSUE TITLE
Version trouble

### ISSUE THREAD

**Issue by PouletAxel** [mirnylab/cooltools#150]
Hi,
I had one problem of version, on function if you install cooltools with pip install or pip install git+https://github.com/mirnylab/cooltools.git

the two version are 0.3.0 but the name of one parameters change --ignore-diags with git and with the pip install it is --drop-diags 
It is only to inform you
Best
Axel

**Comment by nvictus** [comment]
Hi Axel! Thanks for informing us! I've tagged master as a `-dev` version to make it clear that it's the "bleeding edge" version.

**Comment by nvictus** [comment]
OK, now I see the problem. We made a v0.3.1 [release](https://github.com/mirnylab/cooltools/releases/tag/v0.3.1) to make Zenodo mint a DOI, but we didn't  actually increment the version number in `__init__.py` and we didn't upload to PyPI either...

Thank you for catching this!

**Comment by nvictus** [comment]
So, to resolve this: the v0.3.1 release on github can be safely ignored because it won't end up on PyPI. The next cooltools release will v0.4.0.

**Comment by PouletAxel** [comment]
thanks
