### ISSUE TITLE
distributed.core - WARNING - Event loop was unresponsive in Worker

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooltools#17]
This is the error I get when trying to run `cooltools compute_expected' on our cluster.
Here is the full trace (this line with different number of seconds is repeated many times):

```
distributed.core - WARNING - Event loop was unresponsive in Worker for 1.24s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
```
This creates an empty output file. This seems to be a known issue related to moving large amounts of data, as suggested in the warning - however I am not moving large amounts of data I guess. I tried specifying a very small chunksize, and this doesn't help. Is there a minimal code example I could try to run on the cluster to try to check whether there is something wrong with hole setup? I've never used `distributed` myself, so don't know what to try.

**Comment by nvictus** [comment]
What versions of distributed and dask are you using? This issue came up for me too last month, but after an upgrade -- I'm not sure exactly what I did -- it seems to be fine.

**Comment by Phlya** [comment]
dask                          0.17.1
dask-core                  0.17.1
distributed                 1.21.3

**Comment by nvictus** [comment]
no longer relevant
