### ISSUE TITLE
fill_diagonal for negative diagonals

### ISSUE THREAD

**Issue by gfudenberg** [mirnylab/cooltools#32]
cooltools.fill_diagonal not working as expected for negative diagonals

![image](https://user-images.githubusercontent.com/19657573/42006676-3105a198-7a30-11e8-902d-26b4de0bd138.png)

**Comment by nvictus** [comment]
Let's remove it in favor of `set_diag`. The extra `wrap` option is useless. Alternatively, we can make it identical to `set_diag` but not in-place by default, mirroring the other "fill" functions.
