### ISSUE TITLE
genome gc error

### ISSUE THREAD

**Issue by Phlya** [mirnylab/cooltools#34]
Hi. Concerning this part of code:
https://github.com/mirnylab/cooltools/blob/cbb1a0a410560ec80c38a4cd6c38daebaceeb636/cooltools/cli/genome.py#L68-L70

chromsizes_path is not defined here, and so the Error is not raised properly.

**Comment by Phlya** [comment]
Should be bins_path instead, I guess?

**Comment by nvictus** [comment]
yup

**Comment by Phlya** [comment]
Just made a PR to fix it

**Comment by nvictus** [comment]
awesome, thank you! :+1:
