### ISSUE TITLE
disagreement between peak prominence methods

### ISSUE THREAD

**Issue by gfudenberg** [mirnylab/cooltools#4]
_find_insulating_boundaries_dense disagreed with find_peak_prominence_iterative

former = blue, latter = red
![image](https://user-images.githubusercontent.com/19657573/31802081-028000d8-b501-11e7-808f-44dcd31e387b.png)

**Comment by golobor** [comment]
could not reproduce the described issue, but found a disagreement for peaks with a NaN neighbor. Closed. Please feel free to reopen if the issue comes up again.
