### ISSUE TITLE
call_compartments for trans

### ISSUE THREAD

**Issue by betulakgol** [mirnylab/cooltools#44]
call_compartments function does not work when one call compartments for only trans interactions. The command I used: `cooltools call_compartments --contact-type trans --bigwig -o filename filename.cool`
I get the error below:
`  File "/home/ba69w/tools/miniconda3/envs/cooler-env/lib/python3.6/site-packages/cooltools/cli/call_compartments.py", line 157, in call_compartments
    eigvals.to_csv(out_prefix + '.' + contact_type + '.lam.txt', sep='\t', index=False)
AttributeError: 'numpy.ndarray' object has no attribute 'to_csv'`

Thank you for your help!

**Comment by Phlya** [comment]
https://github.com/mirnylab/cooltools/issues/40

**Comment by sergpolly** [comment]
closing, @betulakgol fixed it
