### ISSUE TITLE
What does saddle plot mean?

### ISSUE THREAD

**Issue by QianzhaoJ** [mirnylab/cooltools#52]
Hi ：
    Thanks for developing such a powerful tool !
    But I'm so confused  about the meaning of a saddle plot . I guess it may represent the genomic changes of A/B compartment . But I don't know how it works . Could you explain the biological significance which it represents ?
   Thank you in advance !

**Comment by mimakaev** [comment]
Hi Qianzhao, 

The saddle plot shows enrichment of interactions as a function of the compartment vector. The science behind the plot is described in our Nature Methods paper https://www.nature.com/articles/nmeth.2148 

Max
