### ISSUE TITLE
How to calculate eigenvector

### ISSUE THREAD

**Issue by zhqu1148980644** [mirnylab/cooltools#55]
https://github.com/mirnylab/cooltools/blob/6a6857f7cc973ba589d8b47ae90b9325d3190e8b/cooltools/eigdecomp.py#L265-L269

I tested two other ways of finding A/B compartment.
1:
```
Abar = np.mean(A[is_valid])  # center by scalar mean 
O = (A - Abar)
O[is_bad_bin, :] = 0
O[:, is_bad_bin] = 0
eigvecs, eigvals = numutils.get_eig(O, n_eigs, mask_zero_rows=True)
```
2:
```
Abar = np.mean(A[is_valid])  # center by scalar mean
O = (A - Abar)
O[is_bad_bin, :] = 0
O[:, is_bad_bin] = 0
u, s, vh = numpy.linalg.svd(O)
```
Their results of first eigenvector/principal coponennt are **not equal** while their separation of A/B compartment and plot of A/B compartment (use `matplotlib.pyplot.fill_between`) are **quite similiar**.

And the original way of finding compatment A/B in the paper use the second way i.e. use SVD/PCA

> Lieberman-aiden, Erez.. 2009 . Comprehensive Mapping of Long-Range Interactions Reveals Folding Principles of the Human Genome

So,my question is how to deduce the formula in your code and waht's the relationship among these three ways.
I would sincerely appreciate your answer.

**Comment by mimakaev** [comment]
It is likely because of missing regions, which are rows/columns that are all zeroes the Hi-C map . We do not include them in the calculation of the eigenvector because they introduce error. Direct calculation would need to have them masked.

**Comment by zhqu1148980644** [comment]
@mimakaev 
thanks for your reply.I made a little change to my original question.  The point is principal components uses eigenvectors of matrix XtX while the formula which is written in the code directly use eigenvectors of matrix X(both X has been centered by rowmean)

**Comment by mimakaev** [comment]
Hi. 

As I recall, eigenvectors done by PCA and by eigenvector decomposition of mean-centered matrix are the same if your matrix is balanced and zero-only rows/columns are excluded. This comes from the fact that centering by colmean of a balanced matrix leaves the matrix symmetric. In that case, covariance matrix calculated in PCA is equivalent to dot(X-1, X-1). And  dot(X-1, X-1) has the same eigenvectors as (X-1), and squared eigenvalues. 

Max

**Comment by zhqu1148980644** [comment]
@mimakaev  if this (dot(X-1,X-1))means XtX？
why eigenvectors of XtX equals X。
My test shows these three results of  vector are not equal at all.

**Comment by zhqu1148980644** [comment]
The matrix is already symmetric.  Thanks again. Finally figured out what you mean.
