### ISSUE TITLE
Identifying TAD regions based on Insulation and boundary regions

### ISSUE THREAD

**Issue by ancient-learner** [mirnylab/cooltools#64]
Hi
I am trying to Identify the TAD regions for my 4 celltypes and compare genome organization. I used cooltools to calculate insulation and Boundary strengths. Now I got a file like this:
```
      chrom      start   end  bad.bin log2.insulation.score.200000 boundary.strength.200000
136	chr1	5440000	5480000	False	-0.020649192112161416	
137	chr1	5480000	5520000	False	-0.08983408349814538	0.029675768795526164
138	chr1	5520000	5560000	False	-0.08972210924370548	
139	chr1	5560000	5600000	False	-0.06015831470261922	
140	chr1	5600000	5640000	False	-0.1040748702567965	0.12724864273066733
141	chr1	5640000	5680000	False	0.001142369018030384	
142	chr1	5680000	5720000	False	0.023173772473870813	
143	chr1	5720000	5760000	False	0.01894016732547185	
144	chr1	5760000	5800000	False	0.008149595704109502	
145	chr1	5800000	5840000	False	-0.08470345777294386	
146	chr1	5840000	5880000	False	-0.12960500458292354	
147	chr1	5880000	5920000	False	-0.20928351089262404	0.01908011154280434
148	chr1	5920000	5960000	False	-0.1959714279880635	
149	chr1	5960000	6000000	False	-0.1902033993498197	
150	chr1	6000000	6040000	False	-0.21942210559882303	
151	chr1	6040000	6080000	False	-0.29760171736085267	
152	chr1	6080000	6120000	False	-0.5228255051589277	
153	chr1	6120000	6160000	False	-0.5765369709803618	0.6556568119024123
154	chr1	6160000	6200000	False	-0.4908568131216154	
155	chr1	6200000	6240000	False	-0.32649592017236534	
 
```
 For further analysis I want to get the aggregated bins like

```
chr1	5440000 6120000  Agrregated Insulation_score
chr1   6160000  6280000 Aggregated Insulation_score
```
  
Is there any way in cooltools to get this>

**Comment by Phlya** [comment]
Just yesterday I did it in python. This also filters by strength of boundaries (improves annotation a lot) and removes very long TADs. Note, that it combines the right end of the left boundary and the left end of the right boundary, which is not necessarily the best thing to do (it will create a single-bin gaps between the TADs), but doesn't matter in general in the grand scheme of things (but also easy to change).
```
res = 100000
win = 1000000
min_bs = 0.1
insul = pd.read_csv('/home/s1529682/eddie/ilia/coolers/Bonev_ES.mm9.mapq_30.1000.mcool_%s.insulation_%s.bed'% (res, win), sep='\t')
boundaries = insul[['chrom', 'start', 'end', 'boundary_strength_%s' % win]].dropna()
boundaries = boundaries[['chrom', 'start', 'end']][boundaries['boundary_strength_%s' % win] > min_bs]

TADs = pd.merge(boundaries[:-1].reset_index(drop=True), boundaries[1:].reset_index(drop=True), left_index=True, right_index=True, suffixes=['1', '2'])
TADs = TADs[TADs['chrom1']==TADs['chrom2']]

l = TADs['start2']-TADs['start1']

TADs[l<1.5*10**6][['chrom1', 'end1', 'start2']].to_csv('/home/s1529682/eddie/ilia/beds/TADs_Bonev_ES.mm9.mapq_30.1000.mcool_%s_IS%s_minBS_%s.bed' % (res, win, min_bs), sep='\t', index=False, header=False)
```

**Comment by ancient-learner** [comment]
Nice. Also `np.cumsum(insulation_score) or part.sum(insulation_score)` for those regions would be good as We can use it to define TAD strength.

**Comment by Phlya** [comment]
What insulation score are you summing up?..

**Comment by ancient-learner** [comment]
log2.insulation.score.200000

**Comment by Phlya** [comment]
From where? I don't get why summing up insulation scores for smth should show TAD strength...

**Comment by ancient-learner** [comment]
What is the metric I should use to determine the TAD strength then?

**Comment by Phlya** [comment]
TAD boundary strength is already in the output of cooltools. What do you mean by TAD strength?

**Comment by nvictus** [comment]
Note that `boundary_strength` is a measure of [peak prominence](https://en.wikipedia.org/wiki/Topographic_prominence), but applied to negative peaks, i.e. valleys.

https://github.com/mirnylab/cooltools/blob/master/cooltools/lib/peaks.py#L6
