### ISSUE TITLE
cooltools dump-cworld  does not recognize mcool file

### ISSUE THREAD

**Issue by betulakgol** [mirnylab/cooltools#84]
Hi,
cooltools dump-cworld  does not recognize mcool file
This is the code I run:

```
cooltools dump-cworld --cworld-type matrix  --region  chr1 --balancing-type IC_unity aaa.mcool::/resolutions/50000 aaa.50000.matrix.gz

bash: aaa.mcool::/resolutions/50000: No such file or directory
```
Thank you!

Best,
Betul

**Comment by golobor** [comment]
Hi Betul,
thank you for the bug report!!
I just pushed a commit fixing it - do you mind testing it? It seems to work on my side.
Anton

**Comment by betulakgol** [comment]
I did the follows:

```
pip install git+https://github.com/mirnylab/cooltools.git

cooltools dump-cworld --cworld-type matrix --region 'chr1' --balancing-type IC_unity aaa.mcool::/resolutions/50000 aaa.50000.IC.matrix.gz
Error: Invalid value for "COOL_PATHS": Path "aaa.mcool::/resolutions/50000" does not exist.

```
Thanks Anton!

Betul

**Comment by golobor** [comment]
hi
given the error message, i suspect that cooltools were not updated.
May I ask you to run the same command, but with a minor modification?

pip install -U git+https://github.com/mirnylab/cooltools.git

Thanks!

**Comment by betulakgol** [comment]
Yes, that was the problem. I did pip--force-reinstall and got some other issues but it is working now. Thank you so much!

Best,
Betul

**Comment by golobor** [comment]
yay!
