### ISSUE TITLE
saddle plots for genomic bands - best way to specify options ?

### ISSUE THREAD

**Issue by sergpolly** [mirnylab/cooltools#87]
it seems like adding support for diagonal genomic bands in saddle plot cli is generally useful and interesting - it's essentially would do the same as @jnuebler COMPscore by genomic separation, but can be advantageous for shallow data, and for seeing nuances of compartmentalization - we recently used it in https://www.biorxiv.org/content/10.1101/678474v1 - here is an example:
![genomic_band_saddle](https://user-images.githubusercontent.com/6790270/60113705-5b7b0200-9740-11e9-9cd0-ff8a86fd4c51.png)

My question is what is the best way to add corresponding options to the saddle CLI script ?
diagonal regions #37 ? or should it be like `pairtools select`-type of thing:
```
pairtools select '(chrom1==chrom2) and (abs(pos1 - pos2) < 1e6)'
```
I personally like the general `pairtools`-style,  but maybe it is worth expanding the definition of a `region` - as there would probably be only "diagonal" and "rectangular" regions only  - maybe some crosses and combinations of the two, right ?

**Comment by Phlya** [comment]
I am considering trying this, is there a way this can be currently achieved? Filling unwanted distances in expected with `np.nan`, perhaps?

**Comment by sergpolly** [comment]
hey! @Phlya - yes, that's how we've done it - fill with `np.nan`-s whatever we didn't want to be counted in the saddle calculations
I uploaded that notebook here **https://github.com/dekkerlab/Abramo_2019**
this notebook is a mess, but the key-function, as far as I remember is `make_cis_obsexp_diagband_fetcher` - which you can plug in the "normal" saddle calculator from `cooltools` - the https://github.com/mirnylab/cooltools/blob/f67e626f1146be4f8448e61bff6fbfb179f4be70/cooltools/saddle.py#L205  - i.e. the `getmatrix` argument, as a replacement of this one: https://github.com/mirnylab/cooltools/blob/f67e626f1146be4f8448e61bff6fbfb179f4be70/cooltools/saddle.py#L94

**Comment by sergpolly** [comment]
in this post I was hoping to get some input on how to best generalize such specification of genomic bands - sort of like `regions` argument in `make_saddle` but for genomic separations ...

**Comment by sergpolly** [comment]
by @Phlya suggestion:
```
--min-distance
--max-distance
```

**Comment by sergpolly** [comment]
on the topic of filling diagonals with `nan`-s - https://github.com/mirnylab/cooltools/pull/102#issuecomment-547558264

the `numutils.set_diag` solution by @Phlya seems to be faster than the alternative `getmatrix` the way we've done it - tried on matrices of  `1e3X1e3 , 1e4X1e4, ~1e5X1e5` and using different`min/max_dist` , (just quick and dirty test, but the result is obvious it seems) e.g.:

![diags_nan](https://user-images.githubusercontent.com/6790270/67799642-2539f000-fa5c-11e9-8567-90dfe8261531.png)


perhaps it's the creation of several `matrix.shape` arrays -> `i,j = np.indices(matrix.shape); genomic_separation = np.abs(i-j)`  that is killing the performance ...

Thank you @Phlya again for a beautiful solution!

**Comment by sergpolly** [comment]
case closed I guess ...
