### ISSUE TITLE
`observed_over_expected` fails to compile with numba 0.44.1

### ISSUE THREAD

**Issue by nvictus** [mirnylab/cooltools#90]
For now, I've pinned numba < 0.44 , but we should find out what broke.

**Comment by golobor** [comment]
seems like numba became more strict on compilation warnings.
Fixed!

**Comment by golobor** [comment]
@nvictus review, if possible and close?

**Comment by nvictus** [comment]
Remove the version pinning from `environment.yml' and make a PR . If tests pass on travis, we can merge.

**Comment by golobor** [comment]
done!
