### ISSUE TITLE
gridspec_inches valueError in py36 or py37

### ISSUE THREAD

**Issue by gfudenberg** [mirnylab/cooltools#91]
in jupyter notebook with %matplotlib inline. doesn't throw the error with %matplotlib notebook and works fine in py35 either way... 
![image](https://user-images.githubusercontent.com/19657573/60461132-7b0ba200-9bfa-11e9-8559-f67ca24b2782.png)
![image](https://user-images.githubusercontent.com/19657573/60461154-8ced4500-9bfa-11e9-8b36-4623cff7f3f1.png)
any thoughts @golobor ?

**Comment by golobor** [comment]
fixed! the issue was caused by frameon=False.
I don't remember why i set it, probably, b/c it forced the size of the figure to be exactly the same as the specified? In any case, disabling for now.
